Chore: fixes 'wobbly' targetbox texture when entities move
AscensionGameDev/Intersect-Engine pull request #1096
Opened 2022-03-02 19:35 UTC by Arufonsu

* Should resolve #1095 
* Applied Lathander's idea to prevent the 'wobbly' (trembling looking) effect of the targetbox texture when entities move.
* Removed redundant casts within the 'DrawTarget' method.
* Moved the declaration 'srcRectangle' closer to it's usage.
* Converted to float values the fraction operations for targetTex's Width and Height in order to prevent possible loss of fraction.

2022-03-03 12:23 UTC, Cheshire92 approved these changes

2022-03-06 19:58 UTC, AlexVild submitted a review, later dismissed

2022-03-06 21:49 UTC, lodicolo requested changes

2022-03-06 21:49 UTC, lodicolo commented on Intersect.Client/Entities/Entity.cs
> +                destRectangle.X = (float) Math.Ceiling(GetCenterPos().X - (float) targetTex.GetWidth() / 4);
Can you put this in instead

```csharp
            var targetTex = Globals.ContentManager.GetTexture(Framework.Content.TextureType.Misc, "target.png");
            if (targetTex != null)
            {
                var srcRectangle = new FloatRect(
                    priority * targetTex.GetWidth() / 2f,
                    0,
                    targetTex.GetWidth() / 2f,
                    targetTex.GetHeight()
                );

                var destRectangle = new FloatRect(
                    (float)Math.Ceiling(GetCenterPos().X - targetTex.GetWidth() / 4f),
                    (float)Math.Ceiling(GetCenterPos().Y - targetTex.GetHeight() / 2f),
                    srcRectangle.Width,
                    srcRectangle.Height
                );

                Graphics.DrawGameTexture(targetTex, srcRectangle, destRectangle, Color.White);
            }
```

2022-03-06 22:11 UTC, Arufonsu commented on Intersect.Client/Entities/Entity.cs
> +                destRectangle.X = (float) Math.Ceiling(GetCenterPos().X - (float) targetTex.GetWidth() / 4);
Done 👍🏽

2022-03-06 22:14 UTC, lodicolo approved these changes

2022-03-06 22:14 UTC, merged