Fix lower-case in Server project file
AscensionGameDev/Intersect-Engine pull request #1102
Opened 2022-03-08 19:08 UTC by char32

Fixes lower-case file names in Server.csproj.
Also fixes compilation under Linux with mono/msbuild.

2022-03-09 18:08 UTC, lodicolo commented
@char32 Can you also add yourself to AUTHORS.md under the collaborators section in this PR?

2022-03-09 18:09 UTC, lodicolo requested changes
AUTHORS.md

2022-03-10 12:48 UTC, char32 commented
@lodicolo Ok I added myself. And thanks :-)

2022-03-10 17:45 UTC, lodicolo approved these changes

2022-03-10 17:47 UTC, merged