Fix 1174
AscensionGameDev/Intersect-Engine pull request #1175
Opened 2022-03-31 14:13 UTC by AlexVild

Fixes issues with guild banks where too many slots were being displayed. Adds a new "MaxBankSlots" param in options under BankOptions that allows the dev to configure their absolute maximum bank slots.

Users should definitely:

- Back up their databases
- Run the server, then close it before migrating
- Review the server config's bank slots (Player max slots, guild max slots, max possible slots) values before running the migration.

2022-03-31 14:52 UTC, lodicolo requested changes

2022-03-31 14:54 UTC, Arufonsu requested changes

2022-03-31 14:54 UTC, Arufonsu commented on Intersect (Core)/Config/Options.cs
> +        [JsonProperty("Player")] public PlayerOptions PlayerOpts = new  PlayerOptions ();
unnecessary extra white spacing

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/Options.cs
> +        [JsonProperty("Player")] public PlayerOptions PlayerOpts = new  PlayerOptions ();
Fixed, dunno why that happened

2022-03-31 19:02 UTC, AlexVild commented on Intersect.Client/Interface/Game/Bank/BankWindow.cs
> +            for (var i = 0; i < Options.Instance.BankOpts.MaxBankSize; i++)
Good idea, done.

2022-03-31 19:02 UTC, AlexVild commented on Intersect.Server/Database/PlayerData/Players/Guild.cs
> +            if (count > BankSlotsCount && count <= Options.Instance.BankOpts.MaxBankSize)
done

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/PlayerOptions.cs
> +        public int DefaultBankSize = 100;
Done

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/Options.cs
> +        public static int MaxBankSlots => Instance.PlayerOpts.DefaultBankSize;
Removed static, replaced existing usages

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/Options.cs
> +        public BankOptions BankOpts = new BankOptions();
done

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/Guilds/GuildOptions.cs
> +        public int DefaultGuildBankSlots { get; set; } = 50;
done

2022-03-31 19:02 UTC, AlexVild commented on Intersect (Core)/Config/BankOptions.cs
> +        public int MaxBankSize = 500;
done

2022-04-02 17:05 UTC, Arufonsu commented on Intersect (Core)/Config/Options.cs
> +        [JsonProperty("Player")] public PlayerOptions PlayerOpts = new  PlayerOptions ();
yeah, has happened to me as well 😆 👍🏽

2022-04-03 20:50 UTC, lodicolo approved these changes

2022-04-03 20:51 UTC, merged