Block Function
AscensionGameDev/Intersect-Engine pull request #1209
Opened 2022-04-16 11:27 UTC by WeylonSantana

Resolves #1009

Block worked a few years ago, [this was its original function](https://www.youtube.com/watch?v=TgmhdnsR6TM&ab_channel=AscensionGameDev). But since it stopped working, traces of its code continue to this day. (Blocking properties on the entity, configuration on the server, shortcut button on the client, block action messages, etc.). I decided to repurpose this and rethink the way block works

I will be using these 3 properties
![image](https://user-images.githubusercontent.com/63019821/163673070-95c0c94d-8594-4016-9d72-50dbd6c07159.png)

Block Chance: Chance the user has to successfully block a hit.
Block Amount: When successfully defending, percentage of damage that the block action will decrease.
Block Damage Absorption: When successfully defending and the damage absorbed, a percentage of that damage that will increase the health of the defending user (a kind of reverse lifesteal)

Simple test (we can consider armed or unarmed combat - Absorption not working yet): https://www.ascensiongamedev.com/resources/filehost/6ea7556f566d4ce2f1a7f1606c9ed09b.mp4

2022-04-16 21:35 UTC, WeylonSantana commented
Using the damage absorbed by the shield to increase health is working:
https://www.ascensiongamedev.com/resources/filehost/f597ab556846c4de00daf65318614835.mp4

2022-04-24 16:32 UTC, Arufonsu requested changes

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Client/Interface/Game/DescriptionWindows/ItemDescriptionWindow.cs
> +
Unnecessary extra spacing.

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +            //Check on each attack if the enemy is a player AND if he is blocking.
> //Check on each attack if the enemy is a player AND if he is blocking.

* use singular third-person pronoun:
_//Check on each attack if the enemy is a player AND if **they** are blocking._

source: https://apastyle.apa.org/blog/singular-they

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                    int originalBaseDamage = baseDamage;
use `var`

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                    int blockChance = item.BlockChance;
use `var`

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                    double blockAmount = item.BlockAmount / 100.0;
use `var`

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                    double blockAbsorption = item.BlockAbsorption / 100.0;
use `var`

2022-04-24 16:32 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                        int absorptionAmount = (int)Math.Round(baseDamage * blockAbsorption);
use `var`

2022-04-24 17:39 UTC, Arufonsu approved these changes

2022-04-24 17:48 UTC, Arufonsu commented on Intersect.Server/Entities/Entity.cs
> +                    if (Randomization.Next(1, 101) < blockChance)
what's the main goal of this randomization (?)
if you want to randomize from 1% to 100% then the logic is fine.
but if u want to rand from 0% to 100% (assuming that you are somewhat simulating percentage this way)
then it's 0,101

2022-04-24 17:51 UTC, Arufonsu approved these changes

2022-04-28 23:41 UTC, lodicolo approved these changes

2022-04-28 23:41 UTC, merged