fix: (Day) - Update editor to use appropriate strings for file size/remaining text
AscensionGameDev/Intersect-Engine pull request #1306
Opened 2022-06-22 19:18 UTC by AlexVild

Resolves #1305

2022-06-23 13:11 UTC, WeylonSantana approved these changes

2022-06-23 19:10 UTC, Arufonsu approved these changes

2022-07-10 20:14 UTC, lodicolo commented
@AlexVild Screenshot of fix please

2022-07-10 20:15 UTC, lodicolo requested changes
@AlexVild Screenshot of fix please

2022-07-11 00:27 UTC, lodicolo approved these changes

2022-07-11 00:27 UTC, merged