fix bags with deleted items have slots taken by ghost items
AscensionGameDev/Intersect-Engine pull request #1336
Opened 2022-06-24 01:01 UTC by jcsnider

Resolves #1335

2022-06-24 01:21 UTC, AlexVild approved these changes

2022-06-24 01:21 UTC, AlexVild commented on Intersect.Server/Database/Item.cs
> +                        itm.Set(new Item());
Just wondering - in other places I've seen `Item.Set(Item.Empty)` instead - which do we prefer?

2022-07-06 18:39 UTC, Arufonsu submitted a review, later dismissed

2022-07-06 22:45 UTC, WeylonSantana submitted a review, later dismissed

2022-07-09 17:00 UTC, lodicolo requested changes

2022-07-09 17:00 UTC, lodicolo commented on Intersect.Server/Database/Item.cs
> +
Can you add this as an else condition to the if statement immediately below this?

2022-08-31 17:52 UTC, merged