enhance: custom item attribute respawn timers and custom item despawn timers
AscensionGameDev/Intersect-Engine pull request #1343
Opened 2022-06-24 13:23 UTC by jcsnider

Resolves #1331

2022-07-06 23:12 UTC, WeylonSantana approved these changes

2022-07-10 02:38 UTC, lodicolo requested changes

2022-07-10 02:38 UTC, lodicolo commented on Intersect.Editor/Localization/Strings.cs
> +            public static LocalizedString respawntime = @"Respawn Time (ms):      [0 for server default]";
should the text in `[]` not be a tooltip instead of making the label huge?

2022-07-10 02:38 UTC, lodicolo commented on Intersect.Editor/Localization/Strings.cs
> +            public static LocalizedString DespawnTime = @"Item Despawn Time (ms):     [0 for server default]";
should the text in `[]` not be a tooltip instead of making the label huge?

2022-09-26 04:42 UTC, lodicolo approved these changes

2022-09-26 04:42 UTC, merged