Added crafting requirements to individual crafts
AscensionGameDev/Intersect-Engine pull request #1346
Opened 2022-06-24 14:32 UTC by jcsnider

Resolves #852 since #999 was closed.

This hides the crafts the user is not able to make, so they are unaware that they are being hidden. While I remain open to better clarity over requirements and when things are unlocked I feel like that can be leave to the game dev for now. This pr just implements the initial functionality.

2022-07-06 18:29 UTC, Arufonsu approved these changes

2022-07-10 02:43 UTC, lodicolo requested changes

2022-07-10 02:43 UTC, lodicolo commented on Intersect.Server/Entities/Player.cs
> +                if (!table.Crafts.Contains(craftToCheck.Id))
Isn't `craftToCheck.Id` equal to `id`? If so, this check can be moved to _before_ `CraftBase.Get(id)` and avoid an expensive lookup call.

2022-07-10 02:43 UTC, lodicolo commented on Intersect.Server/Entities/Player.cs
> +                    return;
In general I would prefer we keep return statements inside of explicit braces.

2022-08-31 19:56 UTC, merged