Custom Animations
AscensionGameDev/Intersect-Engine pull request #1347
Opened 2022-06-26 14:46 UTC by WeylonSantana

resolves discussion: #1198 and feature:  #1199

Added to the Class Editor, Item Editor and Spell Editor, a new field for entering text, allowing users to add their own _"animations".

If the image name entered does not exist or is null, it will try to use the default _attack, _weapon/shoot, _cast.

If there is no _attack, _weapon/shoot, _cast, the behavior continues the normal default intersect.

Paperdolls support the new animations defined in the editor.

In the case of items, if the weapon has a custom animation
the _shoot will be ignored and the custom animation will be prioritized.
_shoot will only be used if the weapon is projectile and does not have custom animation.

2022-07-10 20:04 UTC, lodicolo commented
@WeylonSantana Can you provide a clip demonstrating the custom animations?

2022-07-12 13:11 UTC, WeylonSantana commented
All working now

2022-07-24 03:58 UTC, lodicolo requested changes
@WeylonSantana I would like a demo video showing this with paperdolls too.

2022-07-24 03:58 UTC, lodicolo commented on Intersect (Core)/GameObjects/ClassBase.cs
> +        public string SpriteAttackAnimation { get; set; }
I think this should be `AttackSprite` instead.

2022-07-24 03:58 UTC, lodicolo commented on Intersect (Core)/GameObjects/ItemBase.cs
> +
`WeaponSprite`

2022-07-24 03:58 UTC, lodicolo commented on Intersect (Core)/GameObjects/SpellBase.cs
> +
`CastSprite`

2022-07-24 03:58 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmItem.Designer.cs
> +            this.txtSpriteAttackAnimation = new DarkUI.Controls.DarkTextBox();
I think this should be a dropdown like other sprite selectors.

2022-07-24 03:58 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmSpell.Designer.cs
> +            this.txtSpriteCastAnimation = new DarkUI.Controls.DarkTextBox();
I think this should be a dropdown like other sprite selectors.

2022-07-24 03:58 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmClass.Designer.cs
> +            this.txtSpriteAttackAnimation = new DarkUI.Controls.DarkTextBox();
I think this should be a dropdown like other sprite selectors.

2022-08-28 13:52 UTC, WeylonSantana commented
moved to #1422

2022-08-31 23:09 UTC, WeylonSantana commented
using this
![image](https://user-images.githubusercontent.com/63019821/187077291-2e1d39bf-c25e-4c05-8a92-47eaf4529ba1.png)
and this
![image](https://user-images.githubusercontent.com/63019821/187077304-d85000eb-c6ae-4b8b-baf8-e9a9a0ae2917.png)

for testing

https://user-images.githubusercontent.com/63019821/187078265-6c3a1120-96e0-4285-992d-dfce1f0d1173.mp4


https://user-images.githubusercontent.com/63019821/187078358-a8562fce-17b5-4f3b-a228-5051f0606912.mp4

2022-09-25 18:48 UTC, lodicolo approved these changes

2022-09-25 18:48 UTC, merged