fix: equipment color in character window
AscensionGameDev/Intersect-Engine pull request #1678
Opened 2022-12-10 21:55 UTC by Arufonsu

* fixes an unwanted behavior within the character window where the player's equipped gear wasn't properly drawn with their corresponding color values.
* chore: simplified some gender checks by converting them into '?:' expressions.

### Before:
![imagen](https://user-images.githubusercontent.com/17498701/206876614-6bd53548-32fa-49ed-a5dd-7e799c1097d3.png)

### After:
![imagen](https://user-images.githubusercontent.com/17498701/206876693-c54d122b-9204-41d5-8a5a-638b538a9c69.png)

2022-12-10 23:08 UTC, WeylonSantana approved these changes

2022-12-21 21:07 UTC, lodicolo requested changes

2022-12-21 21:07 UTC, lodicolo commented on Intersect.Client/Interface/Game/Character/CharacterWindow.cs
> +                                PaperdollPanels[z].RenderColor = itemData.Color;
`if (ItemBase.TryGet(itemNum, out var itemDescriptor)`

Makes no sense to query for the item twice.

2022-12-21 21:07 UTC, lodicolo commented on Intersect.Client/Interface/Game/EntityPanel/EntityBox.cs
>                                  paperdollPanel.RenderColor = itemdata.Color;
Same `if (ItemBase.TryGet(itemNum, out var itemDescriptor)` change needed.

2022-12-30 21:40 UTC, lodicolo approved these changes

2022-12-30 21:41 UTC, merged