Fix: glitched listbox even and hovered rows
AscensionGameDev/Intersect-Engine pull request #1695
Opened 2022-12-31 18:17 UTC by Arufonsu

* Fixes an issue where list box elements that are selected and hovered, are drawn with the selected texture instead of the hovered texture.
* Realigned listbox rows.
* Fixes glitchy and misaligned even rows.
* Should resolve #1648
* [Reworked assets with better looking listbox rows](https://github.com/AscensionGameDev/Intersect-Assets/pull/35)

### Preview:

https://user-images.githubusercontent.com/17498701/210152332-a22f030f-c421-42a7-92ef-4fd7a24b59c3.mp4

2023-01-02 22:47 UTC, lodicolo requested changes
I see no difference between the even and odd rows in the preview? I would have expected it to based on the bug.

2023-01-02 22:56 UTC, Arufonsu commented
> I see no difference between the even and odd rows in the preview? I would have expected it to based on the bug.

Updated the PR information with:

### Before:

![imagen](https://user-images.githubusercontent.com/17498701/210283236-1ff2b98a-8f61-4d00-bb82-4ff6abe432db.png)

![imagen](https://user-images.githubusercontent.com/17498701/210283287-ec4f62f1-d74b-4814-a082-e91e4df1e223.png)

2023-01-03 04:54 UTC, Arufonsu commented
More graphic examples:

![imagen](https://user-images.githubusercontent.com/17498701/210301907-f8d3c2ce-fce1-4ef9-bc6c-0ee6536e64ca.png)

![imagen](https://user-images.githubusercontent.com/17498701/210301834-8c906095-8629-4059-b129-60d88244ea59.png)

![imagen](https://user-images.githubusercontent.com/17498701/210301841-3eb9708e-95ba-4c46-88d2-a0d02da62230.png)

![imagen](https://user-images.githubusercontent.com/17498701/210301886-2ec1a6a8-3628-4312-b6d5-b023b4d941b4.png)


![imagen](https://user-images.githubusercontent.com/17498701/210301872-25df5aae-1f6b-4f6d-a637-4e32716a009e.png)

![imagen](https://user-images.githubusercontent.com/17498701/210301877-ded27d48-5339-4793-a958-3c4d1f5e2c57.png)

2023-01-03 21:46 UTC, lodicolo commented
@Arufonsu So my expectation is that _non-selected rows_ have zebra-striping, not vertically inverting the graphic for the selected row (that doesn't help with accessibility in the slightest).

There are essentially 3 colors for rows:
- background (unselected odd row)
- semi-inverted background (unselected even row) -- semi-inverted meaning it doesn't need to be a perfect inverse, it can be something like a 25% brightness if the background is black, or 75% brightness if background is white
- different color (selected row, doesn't matter if the row is odd or even)

[Zebra striping example (with link to article on its usefulness)
![image](https://user-images.githubusercontent.com/1476550/210446190-1e90e1fd-644a-4dd3-b2b1-62a347cf846c.png)](https://alistapart.com/article/zebrastripingdoesithelp/)

[Example table with me highlighting (aka "selection") a given row while maintaining zebra striping -- the three colors being gray, white, blue (not necessarily the colors we would be using, just an example)
![image](https://user-images.githubusercontent.com/1476550/210446433-032760ce-56a7-46be-9c77-c0c7ff58919e.png)](https://www.w3schools.com/howto/howto_css_table_zebra.asp)

2023-01-04 04:08 UTC, Arufonsu commented
> zebra-striping

i see, okay, i can work around the assets to achieve this effect, but as for the code changes, this should be all we need to fix the initial misaligned / wrong sprite position from which Gwen was reading the rows sprites for even rows.

I'll work a bit with a skin to achieve what you just described tomorrow.

2023-01-08 00:53 UTC, Arufonsu commented
Just opened the following https://github.com/AscensionGameDev/Intersect-Assets/pull/37

https://user-images.githubusercontent.com/17498701/211175865-f10e6a99-f4bf-4e28-a716-4310eee43fdb.mp4

2023-01-22 20:07 UTC, lodicolo approved these changes

2023-01-22 20:07 UTC, merged