chore: overhead hp bar
AscensionGameDev/Intersect-Engine pull request #1707
Opened 2023-01-20 20:08 UTC by Arufonsu

* Simplified code, tested and covered all scenarios.

2023-01-22 13:37 UTC, WeylonSantana approved these changes

2023-01-23 23:50 UTC, Arufonsu commented
For the record: the following was untested until now 🧪 


https://user-images.githubusercontent.com/17498701/214177794-c7473780-2074-4add-985a-7edd53dc50ae.mp4

2023-02-05 19:55 UTC, lodicolo requested changes

2023-02-05 19:55 UTC, lodicolo commented on Intersect.Client/Entities/Entity.cs
> +                return (GetType() == typeof(Entity) && Globals.Database.NpcOverheadHpBar) ||
Check IsHovered first, then shield, then HP, and only then should you check the entity type.

This should also be broken up into multiple if statements so it isn't such a long line.

2023-02-05 19:55 UTC, lodicolo commented on Intersect.Client/Entities/Player.cs
> +                return userPreference || IsHovered;
Revert this. This is not more readable, and forces expensive operations to happen before IsHovered which is a much less costly check.

The original structure and order was very intentional.

2023-03-02 00:46 UTC, lodicolo requested changes

2023-03-02 00:46 UTC, lodicolo commented on Intersect.Client/Entities/Player.cs
> +                return userPreference;
Get rid of this extra variable, and all of the `else` keywords.

Just return true (and return <the last if statement>)

2023-03-02 20:19 UTC, lodicolo approved these changes

2023-03-02 20:20 UTC, merged