re-design editors windows
AscensionGameDev/Intersect-Engine pull request #1864
Opened 2023-08-13 01:09 UTC by WeylonSantana

2023-08-13 01:16 UTC, WeylonSantana commented
/helptest

2023-08-16 23:42 UTC, lodicolo requested changes

2023-08-16 23:42 UTC, lodicolo commented on Intersect.Editor/Localization/Strings.cs
> +            public static LocalizedString stackoptions = @"Stackable?";
Since you are adding this it should be in PascalCase but the name would be better also as `Stackable`.

2023-08-26 21:57 UTC, lodicolo requested changes

2023-08-26 21:57 UTC, lodicolo commented on Intersect.Editor/Localization/Strings.cs
>              public static LocalizedString stackable = @"Stackable?";
Duplicate? Just use the original `stackable`

2023-08-28 13:54 UTC, WeylonSantana commented
done
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/cad19576-157c-4725-bae0-94db27cae618)

2023-08-28 16:44 UTC, lodicolo approved these changes

2023-08-28 20:45 UTC, merged