enhancement: trigger cooldown timer by event equip command
AscensionGameDev/Intersect-Engine pull request #2175
Opened 2024-03-12 02:06 UTC by Arufonsu

resolves #1789 
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/dc0dffdf-8eac-4d1f-90e2-404fa7487e94)
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/5b46d876-01d3-4bfa-a6f1-35ea96fac1c9)

originally made by @WeylonSantana 
https://github.com/AscensionGameDev/Intersect-Engine/pull/1831

updated and solved conflicts

2024-03-12 18:44 UTC, WeylonSantana submitted a review, later dismissed

2024-03-13 01:30 UTC, AlexVild requested changes
Cheeky tiny comments

2024-03-13 01:30 UTC, AlexVild commented on Intersect.Editor/Forms/Editors/Events/Event Commands/EventCommand_EquipItem.cs
> +            if(chkUnequip.Checked)
space here after `if` :>. Just to conform to the global styling.

2024-03-13 01:30 UTC, AlexVild commented on Intersect.Server.Core/Entities/Player.cs
> +                if(updateCooldown)
space here after `if` :>. Just to conform to the global styling.

2024-03-13 17:31 UTC, WeylonSantana approved these changes

2024-03-17 14:57 UTC, AlexVild approved these changes

2024-03-17 15:31 UTC, merged