feature: adds new event triggers to items
AscensionGameDev/Intersect-Engine pull request #2208
Opened 2024-03-29 15:28 UTC by AlexVild

Resolves #2181 

Adds the following options to the Item editor:

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/8580915/7ff338e8-f7c6-4d87-be90-2db9fd749968)

Have tested these and they all work to my knowledge.

2024-03-29 19:40 UTC, Mighty-Professional submitted a review, later dismissed

2024-03-30 18:21 UTC, Mighty-Professional approved these changes

2024-03-30 20:13 UTC, WeylonSantana requested changes

2024-03-30 20:17 UTC, WeylonSantana commented
I have one more extra thing to say, the selection is very strange in the editor, especially if you intend to use the mouse scroll


https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/7cdc6e9c-67b4-4755-b972-7921928492b0

2024-03-30 20:24 UTC, AlexVild commented on Intersect (Core)/GameObjects/ItemBase.cs
> +            set => EventTriggers = JsonConvert.DeserializeObject<Dictionary<ItemEventTriggers, Guid>>(value ?? "") ?? new Dictionary<ItemEventTriggers, Guid>();
fixed

2024-03-30 20:24 UTC, AlexVild commented
@WeylonSantana Fixed the editor issue

2024-03-31 12:27 UTC, WeylonSantana approved these changes

2024-03-31 19:09 UTC, Arufonsu approved these changes

2024-03-31 19:09 UTC, Arufonsu commented on Intersect.Server.Core/Entities/Entity.cs
> +
Hello, gave this PR a try and it seems good so far, just wanted to know though, why was this one call changed outside the previous conditional branches?
as for the rest, tested with a pair of items, so far seems to behave as expected, approved 👍🏽

2024-04-06 02:11 UTC, merged