projectile refactoring: fixes, docs, enhancements
AscensionGameDev/Intersect-Engine pull request #2295
Opened 2024-06-30 17:50 UTC by Arufonsu

- projectile related code has been refactored, documented and commented.
- renamed variables to follow current Intersect's naming conventions.
- fixed variable typos.
- removed unused variables, libraries and imports.
- a lot of methods have been merged into one (GetProjectileOffset, GetRange, FindProjectileRotation) for better organization.
- created AdjustPositionOnMapBoundaries methods for better organization within CheckForCollision (server and client)
- Suppress finalization to optimize garbage collection on projectile disposal (client), this is important for performance and to prevent the finalizer from running.
- fixes server crash due to IndexOutOfRangeException when attacking across maps and when NPCs change maps (#2287).
- fixes projectiles not crossing map boundaries when stepping into more than one boundary (ie. diagonal crossing maps) (#2291).
- fixes server crash due to Z Dimension and Z block level issues with projectiles (bug was discovered while working on this).
- fixes projectile issues when stepping into Z block attributes, now they are destroyed when they are supposed to (this never worked as intended).
- Linear interpolation improvements (client): we had time as a constant, this caused the two problems: non linear movement and the object not actually reaching the target position visually, so now, linear interpolation is dinamically based on the elapsed time since the projectile was spawned. Also, The interpolation factor is now clamped to ensure that the projectile does not overshoot its target position.
- GetProjectileLerping considers Options.Instance.Processing.ProjectileUpdateInterval in order to visually adjust projectiles according to the server update intervals
- Pattern Matching Enhancements: specifically the use of the switch expression with pattern matching introduced in C# 8.0 and enhanced in later versions. The use of the or keyword to combine multiple patterns in a single case is a feature of these enhancements, allowing for more concise and readable code when checking for multiple conditions. (GetRange, FindProjectileRotation.

### Preview

(projectiles across maps - diagonally - map edges - fixes #2287)

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/7269990d-da6d-4470-bd1a-5c7897496886

(fixes #2287)

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/68e40039-508f-4ee0-bb7f-6d664729cb3e

(ZD block levels fixed for projectiles, they are *actually* destroyed when they should now - also doesn't crashes the server with homing nor direct projectiles anymore)
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/18ae3204-8d3e-4d79-b9db-a0262449040b)

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/4c1efac3-7ff5-4b00-a342-628e73d8466d

(Linear interpolation visual improvements)

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/5e4fb4e2-5381-4f74-a9ed-a58e19221792

2024-07-01 03:22 UTC, WeylonSantana requested changes

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +            // Iterate over all possible spawn locations within the defined width and height
remove

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                    // Iterate over all possible directions a projectile can be spawned in
remove

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                                FindProjectileRotationDir(Dir, (Direction)d), // Calculate the rotation direction
remove comment

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                            // Check for collision at the spawn location, mark as dead if collision is detected
remove comment

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                    if (!spawn.ProjectileBase.HomingBehavior && !spawn.ProjectileBase.DirectShotBehavior &&
add a comment here, something like "grapple hooks are only allowed in the default projectile behavior"

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +        private float GetProjectileOffset(bool isXAxis, ProjectileSpawn spawn)
too much nesting, from what I see only the first if can be inverted here

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/b3256f73-3fbf-4816-adda-cfb5196a0c7a)

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                        if (isXAxis) // Horizontal (X) calculation
remove comment

2024-07-01 03:22 UTC, WeylonSantana commented on Intersect.Server.Core/Entities/Projectile.cs
> +                        else // Vertical (Y) calculation
remove comment

2024-07-01 23:14 UTC, Arufonsu commented on Intersect.Client/Entities/Projectiles/Projectile.cs
> +                    // Suppress finalization to optimize garbage collection.
will leave the informative comment under it though:
`// This is important for performance and to prevent the finalizer from running.`

2024-07-01 23:23 UTC, Arufonsu commented on Intersect.Client/Entities/Projectiles/Projectile.cs
> +                                    _spawns[s].Z
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/c8fd68b5-8eaa-495b-8b81-39f7434fb48c)

2024-07-02 00:49 UTC, WeylonSantana commented on Intersect.Client/Entities/Projectiles/Projectile.cs
> +                    // Suppress finalization to optimize garbage collection.
Shouldn't this information be in the method documentation?

2024-07-03 01:31 UTC, WeylonSantana approved these changes

2024-07-03 01:36 UTC, merged

2024-07-03 01:36 UTC, Arufonsu commented
Thanks to @WeylonSantana for reviewing, we ended up with a very clean and organized PR 🎊