Add cooldown groups to items
AscensionGameDev/Intersect-Engine pull request #355
Opened 2020-10-01 17:34 UTC by Azurebeats

resolves #234 

Adds a new field to items called a Cooldown Group. These groups can be configured through the server configuration.
[mage1](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/939a2f04beaae886b8386fdd6c3f6b77.png)

Once set up, they can be configured through the item editor on each item (defaulting to none). Any item then sharing that group in a user's inventory will go on cooldown with their respective cooldowns upon usage of one of these items.

[Image2](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/f7b970027bf8a40ada53cbddc4969f8b.png)
[Image3](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/0909b6e4b0b1b533ec0d4f51ac4854bc.gif)

2020-10-01 21:20 UTC, jcsnider approved these changes

2020-10-02 05:35 UTC, Azurebeats commented
As discussed with @lodicolo , will be changing this to not be taken from the server config but a user enterable field stored as a string in the database instead for future localisation plans.

2020-10-03 18:31 UTC, jcsnider commented
Code looks okay.. but there are a few bugs I think if I understand how this should work...

My setup:
Blue Mana Pot (10s CD)
Red Mana Pot (5s CD)

Scenario 1:
Use the blue mana pot with a 10s cd.
The red mana pot (visually) will only show a 5s cd timer.
![notsynced](https://www.ascensiongamedev.com/resources/filehost/293ef85e356db823a9fed9fc9384b3cf.gif)

Scenario 2:
If you have a cd timer active when you pick up an item in the same cd group, the display shows the item as being ready for use, and it looks like the server actually adds the mana? (Visual bug client, logic bug server?)
[Video](https://www.ascensiongamedev.com/resources/filehost/ad716aa15e5e2e921f1d33f58859fd5c.mp4)

2020-10-03 19:04 UTC, Azurebeats commented
Neither are bugs but how I wrote it.

I'll add a server option to copy the cooldown of the item used to each item in the group or the highest cooldown in the group rather than using the items respective cooldowns.

Could probably also write a fix to mark every item in a group to go on cooldown even if a player doesnt own the items.

2020-10-04 07:00 UTC, Azurebeats commented
I've just changed the functionality to be more in line with what you described through configurable options @jcsnider 

https://github.com/AscensionGameDev/Intersect-Engine/pull/355/files#diff-6a0dfeb01db21d69a9d87c9aa128b5c0

2020-10-06 20:26 UTC, lodicolo requested changes

2020-10-06 20:26 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmItem.cs
> +            //Collect folders and colldown groups
cooldown*

2020-10-06 20:26 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmItem.cs
> +            cmbCooldownGroup.Items.Add("");
`string.Empty`

2020-10-06 20:26 UTC, lodicolo commented on Intersect.Server/Entities/Player.cs
> +                    if (itemBase.CooldownGroup.Trim().Length > 0)
`!string.IsNullOrWhiteSpace(itemBase.CooldownGroup)`

2020-10-06 20:26 UTC, lodicolo requested changes

2020-10-06 20:26 UTC, lodicolo commented on Intersect.Editor/Forms/Editors/frmItem.cs
> +                if (!string.IsNullOrEmpty(((ItemBase)itm.Value).CooldownGroup) &&
`IsNullOrWhiteSpace`

2020-10-11 15:22 UTC, Cheshire92 commented
Added configurable cooldown groups to spells, as well as a config option to make them link/sync up between items and spells.
On top of that, I figured I'd add a rudimentary Global Cooldown system.

![image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/d8d9bf20bc57b0798d410b844d8f931d.gif)

2020-10-11 17:03 UTC, Cheshire92 commented
And finished that as well..

![Image1](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/80068ea5856853c16f05edffb88b8d8b.png)
![Image2](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/6c727909695bece02f6f274433f2841a.gif)

2020-12-20 05:51 UTC, lodicolo submitted a review, later dismissed

2020-12-20 05:52 UTC, lodicolo approved these changes

2020-12-20 23:18 UTC, lodicolo approved these changes

2020-12-20 23:18 UTC, merged