Bonify XP Party for Each Member
AscensionGameDev/Intersect-Engine pull request #773
Opened 2021-06-07 15:03 UTC by dhmhc

Its Resolves: #749

Percentage configured on the gain server.
Ex: 10 = 10%
Monster gives 1000 XP.
1 player, alone, without a party, will win 1000 by killing him.
2 players in a party, will kill this monster.
The Exp that will be divided will be +20%
Then, the monster will now divide 1200 XP, totaling a division of 600 XP for each member.
In short, for each additional member in a group you will gain + 10% xp on top of the xp to be divided for EVERYONE.
The particular EXP I cannot change because there is already a configuration in the items that can add XP individual bonus for each one.

2021-06-23 09:07 UTC, Cheshire92 requested changes

2021-06-23 09:07 UTC, Cheshire92 commented on Intersect (Core)/Config/PartyOptions.cs
> +        public float BonifyExpPercentPerMember = 0;
Shouldn't this be called something like "BonusExperiencePercentPerMember” for clarity?

2021-06-23 09:07 UTC, Cheshire92 commented on Intersect.Server/Entities/Player.cs
>                              var partyMembersInXpRange = Party.Where(partyMember => partyMember.InRangeOf(this, Options.Party.SharedXpRange));
Add .ToArray at the end here.

2021-06-23 09:07 UTC, Cheshire92 commented on Intersect.Server/Entities/Player.cs
> +                            var multiplier = 1.0f + (partyMembersInXpRange.Count() * bonifyXp);
Don't use .Count(), use .Length or .Count from the array we created before.

2021-06-23 09:07 UTC, Cheshire92 commented on Intersect.Server/Entities/Player.cs
> +                            float bonifyXp = Options.Party.BonifyExpPercentPerMember / 100;
bonusExp

2021-06-23 09:07 UTC, Cheshire92 commented on Intersect.Server/Entities/Player.cs
> +                            var partyExperience = (int)(descriptor.Experience * multiplier) / partyMembersInXpRange.Count();
Don't use .Count()

2021-07-03 03:24 UTC, jcsnider commented
Resolved the remaining requests.

2021-07-03 05:38 UTC, Cheshire92 approved these changes

2021-07-03 11:51 UTC, merged