Client Settings Revamp with Categories.
AscensionGameDev/Intersect-Engine pull request #950
Opened 2021-10-12 04:59 UTC by Arufonsu

### About this Pull Request.
* Renamed "Options" to "Settings" in order to keep consistency.
* Added Tabs in order to categorize the client settings.
* "Tabs" are technically Buttons, but we will refer to them as "Tabs" for now, considering what they actually do, visually speaking.
* Game Settings has it's own tab. 
   (it is empty **for now**) 
   -  **Another PR will cover upcoming Game Settings, but first, we need to expand 
   the settings capabilities, see** #936 
   
* Video Settings has it's own tab.
* Audio Settings has it's own tab.
* Keybinding Settings (AKA: "Controls") has it's own tab.
* Apply button behaves as it usually does, but now saves the Keybinding Settings as well.
* When accessing the Settings Window from the Main or Escape Menus, Apply will save and take you back there.
* When accessing the Settings Window from the Main or Escape Menus, Cancel will take you back there without saving.
* When accessing the Settings Window by pressing a configured key, Apply will save and take you back to game.
* When accessing the Settings Window by pressing a configured key, Cancel will take you back to game without saving.

### Preview.
![imagen](https://user-images.githubusercontent.com/17498701/137577497-2e4ac12e-185a-4a05-8a3e-e481b64ad524.png)

![imagen](https://user-images.githubusercontent.com/17498701/137598174-eaffa59f-797d-4088-8675-483a7b8b9d22.png)

![imagen](https://user-images.githubusercontent.com/17498701/137598200-0164ad13-7a97-416d-a1af-4750083964a8.png)

### About the required resources for this PR
* "settings_window.png" replaces "options_horizontal.png".
* "SettingsWindow.json" replaces "OptionsWindow.json".
* "options_dropdown.png" renamed to "settings_dropdown.png"
* Changes to EscapeMenu.json were made due to the "options" renaming.
* Changes to MenuWindow.json were made due to the "options" renaming.

[(Updated 16-10-2021) Download 'resources.zip' with the required files for this PR](https://github.com/AscensionGameDev/Intersect-Engine/files/7358016/resources.zip)
Added the sprites for tabs just in case now, they should be present in the latest asset pack since the addition of the chatbox tabs.
![imagen](https://user-images.githubusercontent.com/17498701/137590889-c3314646-7049-4d4a-bf52-cb8e75227940.png)

NOTE: This PR originally included the 3 new settings for entities info visibility, decided to exclude those for now, because they may still require some discussion and attention in a different PR afterwards, so expect more resource updates on this one !

2021-10-16 07:13 UTC, Arufonsu commented
- Updated the pull request description.
- Updated the pull request preview and resources.
- Reverted the "back" button to "cancel", as previously discussed in discord with @Cheshire92

2021-10-16 13:32 UTC, Cheshire92 requested changes
I'm also not getting the tab graphics set up correctly when I download your resource zip?

![Image](https://www.ascensiongamedev.com/resources/filehost/c84e4c5e7961cb360be317d4e90f3381.png)

2021-10-16 13:32 UTC, Cheshire92 commented on Intersect.Client/Interface/Shared/SettingsWindow.cs
> +        public bool IsVisible()
public bool IsVisible => !mSettingsPanel.IsHidden;

2021-10-16 13:41 UTC, Cheshire92 commented
Also just noticed that Cancel does not return to the escape menu in-game.

2021-10-16 14:17 UTC, Arufonsu commented
> 
> 
> I'm also not getting the tab graphics set up correctly when I download your resource zip?
> 
> ![Image](https://camo.githubusercontent.com/52244f8f7dc87a4e7cce19033b8c4ef064493eff829ad48f4d425e7a9cf0ca19/68747470733a2f2f7777772e617363656e73696f6e67616d656465762e636f6d2f7265736f75726365732f66696c65686f73742f63383465346335653739363163623336306265333137643465393066333338312e706e67)

do you have the latest resources that include the tabs for the chatboxes?
This are the ones being used for tabs, they don't really require any changes.
![imagen](https://user-images.githubusercontent.com/17498701/137590889-c3314646-7049-4d4a-bf52-cb8e75227940.png)

2021-10-16 15:04 UTC, Cheshire92 commented
Ah. I meant that there shouldn't be a difference in labels for the button, it should always be called cancel.. Not randomly cancel, back or exit. :P

However, it should still contextually behave properly.

2021-10-16 16:27 UTC, Arufonsu commented on Intersect.Client/Interface/Shared/SettingsWindow.cs
> +        public bool IsVisible()
[Done 👍🏽 ](https://github.com/AscensionGameDev/Intersect-Engine/pull/950/commits/a5eb8bb077c7beb9c4e46767ebb536997603a69f#diff-5c617a22ae8f6a814cb9e86128e65384b834c70141a564ded35be45f09da8512R586)

2021-10-17 06:42 UTC, Cheshire92 commented
It's honestly really annoying that you keep force pushing stuff as you're forcing me to re-review the entire thing and not just the changes since I can't tell what has or hasn't been changed like this. Could you please stop doing that?

2021-10-17 09:34 UTC, Cheshire92 commented
You've also broken my local version of this now and making me jump through all sorts of hoops to fix it. Well done.
Please never do that again. The easiest solution for me right now is to just delete my local repo and start over with that as a reset just tries to merge your old changes with your new ones somehow.

2021-10-17 10:21 UTC, Cheshire92 approved these changes

2021-10-17 10:21 UTC, merged

2021-10-17 13:24 UTC, Arufonsu commented
> It's honestly really annoying that you keep force pushing stuff as you're forcing me to re-review the entire thing and not just the changes since I can't tell what has or hasn't been changed like this. Could you please stop doing that?


Oh.. my bad, didn't knew that you were working with a local repo, i just wanted the PR to be more in shape and less messy with small commits, as i was fixing small undesired things around.

I didn't really pictured how annoying that  could of been to be honest :( sorry, won't happen again.

Anyway.. thanks a lot for pushing and helping along with this PR, i hope that the idea and changes end up being useful for everyone when it comes to add new client settings :D !

 Regards ~