Chore: Clean up equipment bonus effects, they all do the same thing copy/pasted
AscensionGameDev/Intersect-Engine pull request #975
Opened 2021-10-19 18:42 UTC by Cheshire92

And now with this, they won't be copy/pasted code anymore and we can just use a single method to request their data.

2022-03-20 21:12 UTC, AlexVild approved these changes
A good change, and didn't cause any breaking changes after 2 months of use in my game.

2022-03-21 00:37 UTC, Arufonsu requested changes
need to solve merge conflicts at Intersect.Server/Entities/Combat/Status.cs

2022-03-27 17:02 UTC, Arufonsu approved these changes

2022-03-27 17:03 UTC, Arufonsu commented
solved merge conflicts 👍🏽

2022-03-29 15:29 UTC, merged